apiVersion: v1
kind: Service
metadata:
  name: relay-test
  namespace: kubearmor
spec:
  selector:
    kubearmor-app: kubearmor-relay
  ports:
  - port: 32767
    protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-relay
  namespace: kubearmor
  labels:
    kubearmor-app: kubearmor-relay
spec:
  replicas: 1
  selector:
    matchLabels:
      kubearmor-app: kubearmor-relay
  template:
    metadata:
      labels:
        kubearmor-app: kubearmor-relay
      annotations:
        kubearmor-policy: audited
    spec:
      serviceAccountName: kubearmor
      containers:
      - name: kubearmor-relay-server
        image: harisudarsan/relay-server:latest
        env:
          - name: ENABLE_DASHBOARDS
            value: "true"
          - name: ES_URL
            value: "http://elasticsearch:9200"
          - name: KUBEARMOR_SERVICE
            value: ""
          - name: ENABLE_STDOUT_LOGS
            value: "true"
          - name: ENABLE_STDOUT_ALERTS
            value: "true"
          - name: ENABLE_STDOUT_MSGS
            value: "false"
        imagePullPolicy: Always
        ports:
        - containerPort: 32767
        resources:
          requests:
            cpu: 250m
            memory: 64Mi
          limits:
            cpu: 500m
            memory: 128Mi
